# api/config/schema.yaml
# The list of types and properties we want to use
types:
  Team:
    properties:
      name: ~
      identifier: {range: "Text"}
  Match:
    properties:
      homeTeam: {range: Team}
      awayTeam: {range: Team, }
      startDate: {range: "DateTime"}
      group: {range: Group, cardinality: "(0..1)"}
  Tournament:
    properties:
      name: {range: "Text"}
  Group:
    properties:
      name: {range: "Text"}
      tournament: {range: Tournament}
  MatchDay:
    properties:
      name: {range: "Text"}
      tournament: {range: Tournament}

